### ISSUE TITLE
超级棒！感谢，汉语会出现问题

### ISSUE THREAD

**Issue by xizheng** [suxiaoxin/node-echarts#1]
如题，汉语会出现问题，引入汉语字体，渲染时汉字的长度计算不对

**Comment by suxiaoxin** [comment]
查看源码下demo生成的图片，中文可以正常显示。
请说明下你用的系统，环境等等

**Comment by suxiaoxin** [comment]
@xizheng 
请更新下node-echarts

中文无法显示是因为node-canvas库缺乏相应的字体，node-canvas某一分支提供了加入字体的api,下面是解决办法
1.git clone https://github.com/chearon/node-canvas.git ,然后进入到clone的项目目录，执行npm install

2.下载所需要的字体

3.具体代码如下：

var node_echarts = require('node-echarts');
var path = require('path');
var Canvas =require('./node-canvas');
Canvas.registerFont(path.join(__dirname, "华文仿宋.ttf"), { family: "华文仿宋"});
node_echarts({
    canvas: Canvas,
    font: '12px 华文仿宋',
    path: __dirname + '/中文字体demo.png',
    option: option,
    width:  1000,
    height: 500
})

可查看demo下中文字体demo.js
