### ISSUE TITLE
install 失败

### ISSUE THREAD

**Issue by shanyoushu** [suxiaoxin/node-echarts#5]
C:\Users\Administrator\node_modules\node-echarts\node_modules\canvas>if not defi
ned npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node
-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node ""
rebuild )
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
C:\Users\Administrator\node_modules\node-echarts\node_modules\canvas\build\bind
ing.sln : error MSB3411: 未能加载 Visual C++ 组件“VCBuild.exe”。如果未安装该组
件，请执行下列操作之一: 1)
 安装 Microsoft Windows SDK for Windows Server 2008 和 .NET Framework 3.5；或 2)
 安装
Microsoft Visual Studio 2008。
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v3.5\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\node_modules\node-echarts\node_modules\canva
s
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "node-echarts"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.5 install script 'node-gyp rebuild'.
一定要下一个vs2008么?条件不允许有没有别的办法

**Comment by suxiaoxin** [comment]
@shanyoushu 使用Linux或unix系统
