### ISSUE TITLE
centos7下中文node-canvas

### ISSUE THREAD

**Issue by mashpolo** [suxiaoxin/node-echarts#7]
按照文档，下载node-canvas，执行完npm install后，发现缺少build目录，环境是centos7
但是在mac下，可以成功，依赖都已经安装完，这个是什么原因呢？

**Comment by suxiaoxin** [comment]
之前我在ubuntu机器上试过，没啥问题的，应该是环境哪儿没弄好

**Comment by mashpolo** [comment]
@suxiaoxin 已经搞好了，一个系统语言包没有装上，而且需要手动执行node-gyp编译一次就可以了。
